export const skills = new Map([
    ['Time Management', 0],
    ['Goal Setting', 1],
    ['Emotional Intelligence', 2],
    ['Stress Management', 3],
    ['Critical Thinking', 4],
    ['Self-Discipline', 5],
    ['Financial Literacy', 6],
    ['Networking', 7],
    ['Public Speaking', 8],
    ['Negotiation Skills', 9],
    ['Conflict Resolution', 10],
    ['Adaptability', 11],
    ['Mindfulness and Meditation', 12],
    ['Leadership', 13],
    ['Creativity', 14],
    ['Learning How to Learn', 15],
    ['Physical Fitness', 16],
    ['Organization Skills', 17],
    ['Resilience', 18],
    ['Decision Making', 19],
    ['Empathy', 20],
    ['Self-Reflection', 21],
    ['Conflict Management', 22],
    ['Hobby Development', 23],
])

export const revSkills = new Map([
    [0, 'Time Management'],
    [1, 'Goal Setting'],
    [2, 'Emotional Intelligence'],
    [3, 'Stress Management'],
    [4, 'Critical Thinking'],
    [5, 'Self-Discipline'],
    [6, 'Financial Literacy'],
    [7, 'Networking'],
    [8, 'Public Speaking'],
    [9, 'Negotiation Skills'],
    [10, 'Conflict Resolution'],
    [11, 'Adaptability'],
    [12, 'Mindfulness and Meditation'],
    [13, 'Leadership'],
    [14, 'Creativity'],
    [15, 'Learning How to Learn'],
    [16, 'Physical Fitness'],
    [17, 'Organization Skills'],
    [18, 'Resilience'],
    [19, 'Decision Making'],
    [20, 'Empathy'],
    [21, 'Self-Reflection'],
    [22, 'Conflict Management'],
    [23, 'Hobby Development'],
])
