export const skills = new Map([
    ['Time Management', 0],
    ['Goal Setting', 1],
    ['Emotional Intelligence', 2],
    ['Stress Management', 3],
    ['Critical Thinking', 4],
    ['Self-Discipline', 5],
    ['Financial Literacy', 6],
    ['Networking', 7],
    ['Public Speaking', 8],
    ['Negotiation Skills', 9],
    ['Conflict Resolution', 10],
    ['Adaptability', 11],
    ['Mindfulness and Meditation', 12],
    ['Leadership', 13],
    ['Creativity', 14],
    ['Learning How to Learn', 15],
    ['Physical Fitness', 16],
    ['Organization Skills', 17],
    ['Resilience', 18],
    ['Decision Making', 19],
    ['Empathy', 20],
    ['Self-Reflection', 21],
    ['Conflict Management', 22],
    ['Hobby Development', 23],
])
